# Generated by Django 6.0.1 on 2026-02-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_address_place_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'addresses'},
        ),
        migrations.AddField(
            model_name='address',
            name='store_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='street_name',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='street_number',
            field=models.IntegerField(null=True),
        ),
    ]
